---
title: "Model comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,devtools,rethinking)
```

# LOADING DATA

```{r}
######## LOADING CLASSIFICATION REPORT #################

# Function for loading multiple files
read_plus <- function(flnm) {
    read_csv(flnm) %>% 
        mutate(filename = flnm)
}

# jonfd_electra-small-nordic
classf_report_jonf <- list.files(path = "../data/jonfd_electra-small-nordic", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_jonf['MISS_binary'] <- ifelse(classf_report_jonf$Misclassification == "TRUE", 1, 0) 
classf_report_jonf$model <- 1

# vestinn/ScandiBERT
classf_report_vestin <- list.files(path = "../data/vestinn_ScandiBERT", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_vestin['MISS_binary'] <- ifelse(classf_report_vestin$Misclassification == "TRUE", 1, 0) 
classf_report_vestin$model <- 2

# aelectra
classf_report_aelectra <- list.files(path = "../data/aelectra", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_aelectra['MISS_binary'] <- ifelse(classf_report_aelectra$Misclassification == "TRUE", 1, 0) 
classf_report_aelectra$model <- 3

# xlm-roberta-base
classf_report_XLM_base <- list.files(path = "../data/xlm-roberta-base", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_XLM_base['MISS_binary'] <- ifelse(classf_report_XLM_base$Misclassification == "TRUE", 1, 0)
classf_report_XLM_base$model <- 4

# xlm_roberta_large
classf_report_XLM_large <- list.files(path = "../data/xlm_roberta_large", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_XLM_large['MISS_binary'] <- ifelse(classf_report_XLM_large$Misclassification == "TRUE", 1, 0)
classf_report_XLM_large$model <- 5

# twitter-xlm-roberta
classf_report_twitter_xlm_roberta <- list.files(path = "../data/twitter-xlm-roberta", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_twitter_xlm_roberta['MISS_binary'] <- ifelse(classf_report_twitter_xlm_roberta$Misclassification == "TRUE", 1, 0)
classf_report_twitter_xlm_roberta$model <- 6

# flax
classf_report_flax <- list.files(path = "../data/flax", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_flax['MISS_binary'] <- ifelse(classf_report_flax$Misclassification == "TRUE", 1, 0)
classf_report_flax$model <- 7

# danish-bert-botxo
classf_report_danish_bert_botxo <- list.files(path = "../data/danish-bert-botxo", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_danish_bert_botxo['MISS_binary'] <- ifelse(classf_report_danish_bert_botxo$Misclassification == "TRUE", 1, 0)
classf_report_danish_bert_botxo$model <- 8

# mdeberta-v3-base
classf_report_mdeberta_v3_base <- list.files(path = "../data/mdeberta-v3-base", pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))
classf_report_mdeberta_v3_base['MISS_binary'] <- ifelse(classf_report_mdeberta_v3_base$Misclassification == "TRUE", 1, 0)
classf_report_mdeberta_v3_base$model <- 9

##### COMBINING MODELS #####
modelscombined <- rbind(classf_report_jonf, classf_report_vestin, classf_report_aelectra, classf_report_XLM_base, classf_report_XLM_large, classf_report_twitter_xlm_roberta, classf_report_flax,classf_report_danish_bert_botxo, classf_report_mdeberta_v3_base)


########## LOADING TOPICS ###############
topics <- read_csv("../data/BerTopic/sub_groups_14112022.csv") %>% 
  rename(Text = original_tweet) 



##### MERGING MODELS WITH TOPICS
all_models_w_topics <- merge(modelscombined,topics, by = "Text", all.x = T, all.y = F) %>% 
  rename(run = filename) %>% 
  select(Text, `Predicted Labels`, `True Labels`, new_topic, MISS_binary, run, model)
all_models_w_topics <- all_models_w_topics[complete.cases(all_models_w_topics), ] # removing rows with NA's in topic (50 rows of which 10 were in Arabic)
```

# GETTING ERROR RATES FOR EACH MODEL
```{r}
error_rate_per_run_per_topic <- all_models %>% 
  group_by(new_topic, run, model_) %>% 
  summarise("error_rate_per_run_per_topic" = mean(MISS_binary))

error_rate_per_run_across_topics <- all_models %>% 
  group_by(run, model_) %>% 
  summarise("error_rate_per_run_across_topics" = mean(MISS_binary))

tress <- merge(error_rate_per_run_per_topic, error_rate_per_run_across_topics, by = "run", all.x = T, all.y = F)

quatro <- tress %>% 
  mutate(diff = error_rate_per_run_per_topic - error_rate_per_run_across_topics)

singo <- quatro %>% 
  #filter(new_topic==3) %>% 
  rename(ourmodel = `model_.x`) %>% 
  rename(difference = diff) %>% 
  select(run, new_topic, ourmodel,difference)




```

```{r}
#Basic boxplot
singo %>% 
  filter(new_topic == -1) %>% 
  ggplot(aes(difference))+
  geom_boxplot(width = .5)+
  facet_grid(. ~ ourmodel)

ggplot(df, aes(x=gender, y=sound_level_pref))+
  geom_boxplot(width = 0.5) +
  ggtitle("Box Plot")

#E.g. boxplot with layers
ggplot(df, aes(x=gender, y=sound_level_pref , fill=gender))+
  geom_boxplot(width = 0.5) +
  ggtitle("Box Plot") +
  stat_summary(fun = mean, geom = "point", shape = 23, colour = "Black") + 
  geom_errorbar(stat = 'summary', fun.data = mean_se, width = 0.5)

```


```{r}
final <-  singo %>% 
  select(ourmodel,difference, new_topic)

out <- vector("list", length = length(unique(final$new_topic)))
mod <- vector("list", length = length(unique(final$ourmodel)))

for (i in 1:length(unique(final$new_topic))) {
  j <- ulam(
    alist(
        difference ~ dnorm(mu, sigma),
        mu <- a[ourmodel],
        a[ourmodel] ~ dnorm(0.40, 0.15) ,
        sigma ~ dexp(2) 
    ), data = final, chains = 4, cores = 4)
  mod[[i]] <- j
  out[[i]] <- precis(j, depth = 2)
}

out

precis(mod[1])

plot(coeftab(mod[2]),by.model=TRUE)



mod[1]
mod[2]
f <- mod[3]
f

 #extracting priors
#prior_model3<- extract.prior(mod[1], refresh = 0)

#mod[1]

```





```{r}
###########################
func_TEMP <- function(topic){
  func_df <- final %>% 
    filter(new_topic == topic)
  
  func_model <- ulam(
    alist(
        difference ~ dnorm(mu, sigma),
        mu <- a[ourmodel],
        a[ourmodel] ~ dnorm(0.40, 0.15) ,
        sigma ~ dexp(2) 
    ), data = func_df, chains = 4, cores = 4)
  
  func_precis <- precis(func_model, depth = 2)
  
  return(func_precis)
}

list_precis <- lapply(list(3,4), func_TEMP)

list_precis
#############################
```




